language: php

env:
  matrix:
    - NETTE=nette-2.3
    - NETTE=nette-2.2 COMPOSER=composer-nette_2.2.json

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source

before_script:
  - vendor/bin/phpcs -p --standard=vendor/arachne/coding-style/ruleset.xml --ignore=_* src tests
  - vendor/bin/codecept build

script: vendor/bin/codecept run
